package app.estateagency.enums;

public enum Privilege {
    CHANGE_PASSWORD, CHANGE_CREDENTIALS, CHECK_OFFERS, REPORT_OFFER, ADD_OFFER,
    ADD_AGENT, REMOVE_USER, CHECK_CALENDAR, ADD_MEETINGS, ADD_ADMIN, CHECK_AGENTS, CHECK_REPORTED_ESTATES,
    ADD_DOCUMENTS, CHECK_DOCUMENTS, UPLOAD_PHOTO, CHECK_PHOTOS, SCHEDULE_MEETING
}
