package app.estateagency.enums;

public enum Privilege {
    CHANGE_PASSWORD, CHANGE_CREDENTIALS, CHECK_OFFERS, REPORT_OFFER, ADD_OFFER,
    ADD_AGENT, REMOVE_USER, CHECK_CALENDAR, ADD_MEETINGS, ADD_ADMIN, CHECK_AGENTS, CHECK_REPORTED_ESTATES,
    ADD_DOCUMENTS, CHECK_DOCUMENTS, UPLOAD_PHOTO, CHECK_PHOTOS, SCHEDULE_MEETING, CHECK_MEETINGS,
    FINALIZE_OFFER, BLOCK_OFFER, UNBLOCK_OFFER, CHECK_BLOCKED_OFFERS, CHECK_ARCHIVED_OFFERS,
    ADD_TO_FAVORITES, CHECK_FAVORITES, REMOVE_FROM_FAVORITES, REVIEW_AGENT, CHECK_OFFER_DETAILS
}
